swagger: '2.0'
info:
  title: API Dashboard
  version: ${git.build.version}
schemes:
  - http
  - https
produces:
  - application/json
basePath: "/"
paths:
  /info:
    get:
      tags:
      - "Monitoring"
      summary: "Show the information of the RPC commander"
      description: "Collect and summarize the states of RPC master and workers"
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/InfoResult"
  /traffic:
    put:
      tags:
      - "Monitoring"
      summary: "Show the traffic of RPC invocation"
      description: "Collect and calculate the speed of RPC invocation"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Checked option list"
        required: true
        schema:
          $ref: "#/definitions/OptionList"
      responses:
        200:
          description: "Ok"
  /ping:
    get:
      tags:
      - "Monitoring"
      summary: "Send a ping message to the workers"
      description: "Send a ping message and receive the result"
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/PingResult"
  /exec/pause:
    get:
      tags:
      - "Operation"
      summary: "Pause the RPC requests"
      description: "Pause all of the RPC requests"
      produces:
      - "application/json"
      parameters:
      - name: "duration"
        in: "query"
        description: "The period of pausing (in milliseconds)"
        required: true
        type: "integer"
        default: 10000
      responses:
        200:
          description: "Ok"
  /exec/unpause:
    get:
      tags:
      - "Operation"
      summary: "Unpause the suspended RPC invocation"
      description: "Unpause the suspended RPC invocation"
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
  /exec/activate-detached-worker:
    get:
      tags:
      - "Operation"
      summary: "Switch on/off the using of detached worker(s)"
      description: "Switch on/off the using of detached worker(s)"
      produces:
      - "application/json"
      parameters:
      - name: "state"
        in: "query"
        description: "The state of the worker's state"
        required: true
        type: "boolean"
        default: false
      - name: "class"
        in: "query"
        description: "The name of class will be affected"
        required: false
        type: "string"
      responses:
        200:
          description: "Ok"
  /exec/activate-embedded-worker:
    get:
      tags:
      - "Operation"
      summary: "Switch on/off the using of embedded worker"
      description: "Switch on/off the using of embedded worker"
      produces:
      - "application/json"
      parameters:
      - name: "state"
        in: "query"
        description: "The state of the worker's state"
        required: true
        type: "boolean"
        default: false
      - name: "class"
        in: "query"
        description: "The name of class will be affected"
        required: false
        type: "string"
      responses:
        200:
          description: "Ok"
  /exec/reset-counter:
    get:
      tags:
      - "Operation"
      summary: "Reset the RPC Invocation Counter"
      description: "Reset the RPC Invocation Counter"
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
  /exec/reset:
    get:
      tags:
      - "Operation"
      summary: "Reset the connections"
      description: "Close the connections and make them available for a new call"
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
definitions:
  OptionList:
    type: "object"
    properties:
      MESSAGE_RATE:
        type: "boolean"
        default: false
        description: "Add the message per second rates to the result"
      THROUGHPUT:
        type: "boolean"
        default: false
        description: "Add the throughput information to the result"
  InfoResult:
    type: "object"
    properties:
      status:
        type: "string"
        description: "The status of the RPC master"
        enum:
        - "ok"
        - "failed"
      commander:
        type: "object"
      serverlet:
        type: "object"
      complete:
        type: "boolean"
        default: false
  PingResult:
    type: "object"
    properties:
      status:
        type: "string"
        description: "The status of the RPC master"
        enum:
        - "ok"
        - "failed"
      commander:
        type: "object"
      serverlet:
        type: "object"
      summary:
        type: "string"